SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `handson_library` ;
CREATE SCHEMA IF NOT EXISTS `handson_library` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `handson_library` ;

-- -----------------------------------------------------
-- Table `handson_library`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `handson_library`.`Book` ;

CREATE  TABLE IF NOT EXISTS `handson_library`.`Book` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `TITLE` VARCHAR(100) NULL ,
  `DESCRIPTION` TEXT NULL ,
  `AUTHOR` VARCHAR(100) NULL ,
  `TOTAL_PAGE` INT NULL ,
  `ISBN` VARCHAR(45) NULL ,
  `STATUS` VARCHAR(45) NULL ,
  `YEAR_PUBLISHED` VARCHAR(45) NULL ,
  `COVER_URL` TEXT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `TITLE_UNIQUE` (`TITLE` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
