drop table book if exists;
create table book (
    ID bigint generated by default as identity (start with 1),
    AUTHOR varchar(100) not null,
    COVER_URL varchar(255),
    DESCRIPTION varchar(255) not null,
    ISBN varchar(45) not null,
    STATUS varchar(40) not null,
    TITLE varchar(100) not null,
    TOTAL_PAGE bigint not null,
    YEAR_PUBLISHED varchar(45) not null,
    primary key (ID)
);
alter table book add constraint CONST_UNIQ_TITLE unique (TITLE)